fs3combat:
    default_type: Sailor
  
    
    allow_vehicles: true
    allow_mounts: true
    
    stances:
        Aggressive:
            attack_mod: 2
            defense_mod: -2
        Reckless:
            attack_mod: 4
            defense_mod: -4
        Normal:
            attack_mod: 0
            defense_mod: 0
        Defensive:
            attack_mod: -2
            defense_mod: 2
        Evasive:
            attack_mod: -4
            defense_mod: 4
        Cover:
            attack_mod: 0
            defense_mod: 0
        Hidden:
            attack_mod: 0
            defense_mod: 0


    combatant_types:

        # ----------------------------------------
        # SPECIAL TYPES
        # ----------------------------------------

        Observer:
            hitloc: Humanoid
            #weapon:
            #weapon_specials:
            #armor:

        # ----------------------------------------
        # CUSTOM TYPES
        # ----------------------------------------

        Sailor:
            weapon: Sword
            hitloc: Humanoid
            defense_skill: Reflexes
            armor: None
        Soldier:
            weapon: Musket
            armor: Buff Coat
            hitloc: Humanoid
            defense_skill: Reflexes
        Voodoo:
            weapon: Bolt
            hitloc: Humanoid
            defense_skill: Reflexes
            armor: None
        Unarmed:
            weapon: Brawling
            hitloc: Humanoid
            defense_skill: Reflexes
            armor: None
        Gunner:
            weapon: Culverin
            hitloc: Humanoid
            defense_skill: Reflexes
            armor: None
        Quadruped:
            weapon: Natural Weapons
            hitloc: Quadruped
            defense_skill: Reflexes
            armor: None
        Fish:
            weapon: Natural Weapons
            hitloc: Fish
            defense_skill: Reflexes
            armor: None
        Flier:
            weapon: Natural Weapons
            hitloc: Flier
            defense_skill: Reflexes
            armor: None
        Dinosaur:
            weapon: Natural Weapons
            hitloc: Dinosaur
            defense_skill: Reflexes
            armor: None
        Octopod:
            weapon: Natural Weapons
            hitloc: Octopod
            defense_skill: Reflexes
            armor: None
        Snake:
            weapon: Natural Weapons
            hitloc: Snake
            defense_skill: Reflexes
            armor: None
        Target:
            hitloc: Target
            weapon: Unarmed
            defense_skill: None
            armor: None
        Brig:
            hitloc: Humanoid
            vehicle: Brig of War
            defense_skill: Reflexes
            armor: Brig of War
        Brigantine:
            hitloc: Humanoid
            vehicle: Brigantine
            defense_skill: Reflexes
            armor: Brigantine
        Cutter:
            hitloc: Humanoid
            vehicle: Cutter
            defense_skill: Reflexes
            armor: Cutter
        Sloop:
            hitloc: Humanoid
            vehicle: Sloop
            defense_skill: Reflexes
            armor: Sloop
        Pinnace:
            hitloc: Humanoid
            vehicle: Pinnace
            defense_skill: Reflexes
            armor: Boat
        Lugger:
            hitloc: Humanoid
            vehicle: Lugger
            defense_skill: Reflexes
            armor: Boat
            
    shortcuts:
        "weapons": "weapon"
        "combat/skill": "combat/summary"
        "combat/skills": "combat/summary"
        "combat/slackers": "combat/summary"
        "combat/add" : "combat/join"
        "combat/remove" : "combat/leave"
        "combat/hitlocs" : "combat/hitloc"
        "vehicles": "vehicle"
        "hospitals": "hospital/list"
        "healing": "heal/list"
        "weapons": "weapon"
        "mounts" : "mount"