fs3combat:
    npc_types:
        Goon:
            Default: 4
            Blades: 6
            Bludgeons: 6
            Brawling: 6
            Firearms: 6
            Athletics: 6
            Faith: 6
            Gunnery: 6
            Sailing: 4
            Persuasion: 4
            Composure: 6
            Alertness: 4
            Healing: 4
            Brawn: 2
            Reflexes: 3
            Wounds: 30
        Henchman:
            Default: 6
            Blades: 8
            Bludgeons: 8
            Brawling: 8
            Firearms: 8
            Athletics: 8
            Faith: 8
            Gunnery: 8
            Sailing: 6
            Persuasion: 6
            Composure: 7
            Alertness: 6
            Healing: 6
            Brawn: 3
            Reflexes: 3
            Wounds: 20
        Miniboss:
            Default: 7
            Blades: 10
            Bludgeons: 10
            Brawling: 10
            Firearms: 10
            Athletics: 10
            Faith: 10
            Gunnery: 10
            Sailing: 7
            Persuasion: 7
            Composure: 8
            Alertness: 7
            Healing: 7
            Brawn: 4
            Reflexes: 4
            Wounds: 10
        Boss:
            Default: 8
            Blades: 12
            Bludgeons: 12
            Brawling: 12
            Firearms: 12
            Athletics: 12
            Faith: 12
            Gunnery: 12
            Sailing: 8
            Persuasion: 8
            Composure: 11
            Alertness: 8
            Healing: 8
            Brawn: 5
            Reflexes: 5
            Wounds: 0
        Giant:
            Default: 6
            Blades: 9
            Bludgeons: 11
            Brawling: 11
            Firearms: 9
            Athletics: 11
            Faith: 9
            Gunnery: 9
            Sailing: 6
            Persuasion: 6
            Composure: 12
            Alertness: 6
            Healing: 6
            Brawn: 7
            Reflexes: 4
            Wounds: -10
        Chupacabra:
            Default: 4
            Brawling: 7
            Composure: 6
            Alertness: 6
            Athletics: 5
            Stealth: 6
            Reflexes: 4
            Brawn: 3
            Wounds: 20
        Cipactli:
            Default: 6
            Brawling: 10
            Composure: 8
            Alertness: 5
            Athletics: 4
            Brawn: 7
            Reflexes: 5
            Wounds: -10
        Dingonek:
            Default: 6
            Brawling: 9
            Composure: 8
            Alertness: 5
            Athletics: 4
            Brawn: 4
            Reflexes: 5
            Wounds: 5
        Gbahali:
            Default: 6
            Brawling: 10
            Composure: 9
            Alertness: 5
            Athletics: 4
            Brawn: 5
            Reflexes: 5
            Wounds: 0
        GiantSquid:
            Default: 6
            Brawling: 10
            Composure: 10
            Alertness: 5
            Athletics: 4
            Brawn: 7
            Reflexes: 4
            Wounds: -10
        Kongamato:
            Default: 5
            Brawling: 6
            Composure: 4
            Alertness: 5
            Athletics: 4
            Brawn: 2
            Reflexes: 5
            Wounds: 30
        Megaconda:
            Default: 6
            Brawling: 10
            Composure: 8
            Alertness: 7
            Stealth: 7
            Athletics: 7
            Brawn: 6
            Reflexes: 6
            Wounds: 0
        Megalodon:
            Default: 6
            Brawling: 11
            Composure: 10
            Alertness: 5
            Athletics: 4
            Brawn: 7
            Reflexes: 4
            Wounds: -10
        SeaSerpent:
            Default: 6
            Brawling: 11
            Composure: 7
            Alertness: 6
            Brawn: 6
            Reflexes: 5
            Wounds: -10
        Troglodyte:
            Default: 4
            Brawling: 6
            Blades: 6
            Athletics: 6
            Bludgeons: 6
            Composure: 4
            Alertness: 5
            Brawn: 2
            Reflexes: 3
            Wounds: 40
        Werewolf:
            Default: 6
            Brawling: 9
            Athletics: 9
            Composure: 8
            Alertness: 8
            Brawn: 5
            Reflexes: 5
            Wounds: 10
        Zombi:
            Default: 6
            Brawling: 7
            Athletics: 4
            Composure: 7
            Alertness: 4
            Brawn: 4
            Reflexes: 3
            Wounds: -5