fs3skills:
    bg_skills_blurb: "Background Skills represent arts, sports, hobbies, professions and any other skills not covered by Action Skills.  Background Skills have a descriptive rating.   See [FS3: Background Skills](http://aresmush.com/fs3/fs3-3/chargen/#background-skills) for details.  Background Skills are free-form, so there is no specific list. You can pick anything from Singing to Underwater Basketweaving.  The list below is just some ideas."
    
    background_skills:
        Sciences: "astronomy, botany, chemistry, cartography, mathematics, etc."
        Humanities: "history, literature, philosophy, poetry, etc."
        Professions: "cook, waitress, bartender, carpenter, brewer, blacksmith, etc."
        Games: "chess, cards, dice, etc."
        Arts: "sculpting, painting, sketching, etc."
        Expression: "acting, singing, dancing, playing an instrument, writing, etc."
        Religion: "for non-Faith characters only, Catholicism, Voodoo, Protestantism, etc."
        Hobbies: "gardening, basketweaving, knitting, etc."
        Trivia: "fairy tales, occult, etc."