fs3skills:

    periodic_xp: 1
    
    days_between_learning: 30
    
    max_xp_hoard: 4
    
    xp_cron:
        day_of_week: 
            - Sat
        hour: 
            - 21
        minute: 
            - 00
            
    skills_requiring_training:
        - Faith
        - Healing
        - Gunnery
        
    xp_costs:
        language:
            0: 4
            1: 4
            2: 12
        action:
            0: 3
            1: 1
            2: 2
            3: 3
            4: 5
            5: 10
            6: 12
            7: 12
        background:
            0: 1
            1: 4
            2: 12
        attribute:
            1: 3
            2: 6
            3: 12
            4: 18