game:
    name: "The Eighth Sea"

    category: Fantasy
    
    description: "The Eighth Sea is a game of piracy and the supernatural, of wooden ships, iron men, and the dark myths that slipped through the cracks of civilization. It will explore the edges of reason and the tensions between civilization, outlaws, and the unknown."
    
    website: "http://scrozzle.noderunner.net:8000"
        
    public_game: true
    
    status: Open