game:
    name: "The Eighth Sea"

    category: Fantasy
    
    description: "format_input_for_html(@config['description']) %>"
    
    website: "http://scrozzle.noderunner.net:8000"
        
    public_game: false