game:
    # Name of your game.
    name: "The 8th Sea"

    # Please select the appropriate category to describe your game:
    # "Historical", "Sci-Fi", "Fantasy", "Modern", "Supernatural", "Social", "Other"
    category: Fantasy
    
    # Describe your game.  You may use ansi and other MUSH formatting codes (%r, etc.).
    description: "A High Seas Adventure game set in a world of pirates, monsters and voodoo."
    
    # Your game's website
    website: ""
        
    # true if your game is open for business, false if it is in development, down, or 
    # otherwise not open to the public
    public_game: false