game:
    name: "The Eighth Sea"

    category: Fantasy
    
    description: "format_input_for_html(@config['description']) %>"
    
    website: "http://the8thsea.wikidot.com"
        
    public_game: false