roles:
    default_roles:
       - everyone

    restricted_roles:
        - admin
        - staff
    
    admin_list_roles:
        - admin
        - staff
        - gm
        - builder

    shortcuts:
        "roles" : "role"
        "staff" : "admin"
        "role/set" : "role/assign"
        "role/add" : "role/assign"