server:

    # The host name where your game is running (typically localhost)
    hostname: mush.aresmush.com

    # The port number your game will listen on
    port: 7206

    # The port number your game uses for web connections. This must be different than the regular one.
    websocket_port: 4202

