---
skin:
  line1: '%x!+==~~~~~====~~~~====~~~~====~~~~=====~~~~=====~~~~====~~~~====~~~~====~~~~~==+%xn'
  line2: '%x!------------------------------------------------------------------------------%xn'
  line3: '%x!----[The Game]----------------------------------------------------------------%xn'
  line4: '%x!~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~%xn'
