---
skin:
<<<<<<< HEAD
  line1: '%x!+==~~~~~====~~~~====~~~~====~~~~=====~~~~=====~~~~====~~~~====~~~~====~~~~~==+%xn'
  line2: '%x!------------------------------------------------------------------------------%xn'
  line3: '%x!----[The Game]----------------------------------------------------------------%xn'
  line4: '%x!~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~%xn'
=======
    
    header: "%x!+==~~~~~====~~~~====~~~~=====~~~~=====~~~~====~~~~====~~~~====~~~~~==+%xn"
    footer: "%x!+==~~~~~====~~~~====~~~~====~~~~=====~~~~=====~~~~====~~~~====~~~~====~~~~~==+%xn"
    divider: "%x!------------------------------------------------------------------------------%xn"
    plain: "%x!+==~~~~~====~~~~====~~~~=====~~~~=====~~~~====~~~~====~~~~====~~~~~==+%xn"
>>>>>>> upstream/master
